version: '3'
services:
  python_ai:
    image: anaconda_api:latest
    ports:
      - 5050:8080
    volumes:
       - .:/ai
    tty:
      true